# Generated by Django 2.2.9 on 2020-03-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status post', 'verbose_name_plural': 'status posts'},
        ),
    ]
