# Generated by Django 2.2.9 on 2020-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200310_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
