# Generated by Django 2.2.9 on 2020-03-11 17:25

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20200311_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=status.models.upload_to_image),
        ),
    ]
